// frontend_smoke.cpp - end-to-end test of the C++ mel frontend
// against a byte-level reference produced by NeMo's nemo128.onnx
// preprocessor.
//
// Pipeline under test (transcribe::MelFrontend::compute):
//
//     pcm[176000] -> pre-emphasis -> reflect-pad -> STFT (fp64) ->
//     power spectrum -> mel filterbank -> log -> per-feature normalize
//     -> mel[128, 1101]
//
// Reference: tests/golden/parakeet/jfk-mel.f32 + jfk-mel.json,
// generated by scripts/dump_reference.py from
// nemo128.onnx run on samples/jfk.wav.
//
// The C++ pipeline runs STFT in fp64 to match the ONNX precision; we
// expect to beat the residual that torch's fp32 STFT shows against
// the same golden (~2.4e-4 max). Tolerances are deliberately tight
// so a future regression in any single stage (window, filterbank,
// power, log, normalize) trips the test.

#include "transcribe-mel.h"
#include "wav.h"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <string>
#include <vector>

#ifndef TRANSCRIBE_TEST_SAMPLES_DIR
#  error "TRANSCRIBE_TEST_SAMPLES_DIR must be defined by the build system"
#endif
#ifndef TRANSCRIBE_TEST_GOLDEN_DIR
#  error "TRANSCRIBE_TEST_GOLDEN_DIR must be defined by the build system"
#endif

namespace {

const std::string g_samples_dir = TRANSCRIBE_TEST_SAMPLES_DIR;
const std::string g_golden_dir  = TRANSCRIBE_TEST_GOLDEN_DIR;

int g_failures = 0;

#define CHECK(cond)                                                         \
    do {                                                                    \
        if (!(cond)) {                                                      \
            std::fprintf(stderr, "FAIL %s:%d: %s\n",                        \
                         __FILE__, __LINE__, #cond);                        \
            ++g_failures;                                                   \
        }                                                                   \
    } while (0)

// Read a raw little-endian f32 file produced by scripts/dump_reference.py.
// The shape lives in the json sidecar; we accept it as a parameter
// to avoid taking a json dependency in the test.
bool read_f32(const std::string & path, std::vector<float> & out) {
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        std::fprintf(stderr, "cannot open %s\n", path.c_str());
        return false;
    }
    f.seekg(0, std::ios::end);
    const std::streamoff bytes = f.tellg();
    f.seekg(0, std::ios::beg);
    if (bytes < 0 || (bytes % 4) != 0) {
        std::fprintf(stderr,
                     "%s: bad size %lld (must be a multiple of 4)\n",
                     path.c_str(), static_cast<long long>(bytes));
        return false;
    }
    out.resize(static_cast<size_t>(bytes / 4));
    f.read(reinterpret_cast<char *>(out.data()), bytes);
    return static_cast<std::streamoff>(f.gcount()) == bytes;
}

// Real Parakeet 0.6B frontend config.
transcribe::MelConfig parakeet_config() {
    transcribe::MelConfig cfg;
    cfg.sample_rate  = 16000;
    cfg.num_mels     = 128;
    cfg.n_fft        = 512;
    cfg.win_length   = 400;
    cfg.hop_length   = 160;
    cfg.pre_emphasis = 0.97f;
    cfg.f_min        = 0.0f;
    cfg.f_max        = 8000.0f;
    return cfg;
}

} // namespace

int main() {
    // ----- Load audio -----
    const std::string wav_path = g_samples_dir + "/jfk.wav";
    std::vector<float> pcm;
    std::string err;
    if (!transcribe_cli::load_wav_mono_16k(wav_path, pcm, err)) {
        std::fprintf(stderr,
                     "FAIL load %s: %s\n", wav_path.c_str(), err.c_str());
        return EXIT_FAILURE;
    }

    // ----- Load golden -----
    const std::string golden_path = g_golden_dir + "/jfk-mel.f32";
    std::vector<float> golden;
    if (!read_f32(golden_path, golden)) {
        std::fprintf(stderr,
                     "FAIL read golden %s\n"
                     "regenerate with:\n"
                     "  uv run scripts/dump_reference.py mel-onnx \\\n"
                     "    --onnx <path-to-nemo128.onnx> \\\n"
                     "    --audio samples/jfk.wav \\\n"
                     "    --out tests/golden/parakeet --name jfk-mel\n",
                     golden_path.c_str());
        return EXIT_FAILURE;
    }
    // The golden was generated against samples/jfk.wav (176000 samples)
    // and is shape [128, 1101] = 140928 floats. If the test fails the
    // shape check the golden file is stale.
    constexpr int kExpectedNMels   = 128;
    constexpr int kExpectedNFrames = 1101;
    if (golden.size() !=
        static_cast<size_t>(kExpectedNMels * kExpectedNFrames))
    {
        std::fprintf(stderr,
                     "FAIL golden size: %zu, expected %d\n",
                     golden.size(),
                     kExpectedNMels * kExpectedNFrames);
        return EXIT_FAILURE;
    }

    // ----- Run the C++ frontend -----
    transcribe::MelFrontend mf(parakeet_config());
    std::vector<float> mel;
    int n_mels = 0;
    int n_frames = 0;
    const transcribe_status st =
        mf.compute(pcm.data(), pcm.size(), mel, n_mels, n_frames);
    if (st != TRANSCRIBE_OK) {
        std::fprintf(stderr,
                     "FAIL compute returned %s\n",
                     transcribe_status_string(st));
        return EXIT_FAILURE;
    }
    if (n_mels != kExpectedNMels || n_frames != kExpectedNFrames) {
        std::fprintf(stderr,
                     "FAIL shape: got [%d, %d], expected [%d, %d]\n",
                     n_mels, n_frames, kExpectedNMels, kExpectedNFrames);
        return EXIT_FAILURE;
    }
    if (mel.size() != golden.size()) {
        std::fprintf(stderr,
                     "FAIL mel buffer size: %zu, expected %zu\n",
                     mel.size(), golden.size());
        return EXIT_FAILURE;
    }

    // ----- Element-wise compare -----
    // Tolerances: from RESUME's "Open question 1" the upper bound is
    // < 5e-3 max abs / < 1e-3 mean abs. With fp64 STFT we expect to
    // beat torch's fp32-STFT residual (~2.4e-4 max / ~2e-6 mean) by
    // roughly an order of magnitude. The values below are tight
    // enough to catch a regression in any single stage.
    constexpr double kMaxAbsTol  = 5e-4;
    constexpr double kMeanAbsTol = 5e-5;

    double max_abs   = 0.0;
    double sum_abs   = 0.0;
    int    worst_m   = -1;
    int    worst_t   = -1;
    float  worst_a   = 0.0f;
    float  worst_e   = 0.0f;
    int    nan_count = 0;

    for (int m = 0; m < n_mels; ++m) {
        for (int t = 0; t < n_frames; ++t) {
            const size_t i =
                static_cast<size_t>(m) * n_frames + t;
            const float a = mel[i];
            const float e = golden[i];
            if (std::isnan(a) || std::isnan(e) ||
                std::isinf(a) || std::isinf(e))
            {
                ++nan_count;
                continue;
            }
            const double d = std::fabs(static_cast<double>(a) -
                                       static_cast<double>(e));
            sum_abs += d;
            if (d > max_abs) {
                max_abs = d;
                worst_m = m;
                worst_t = t;
                worst_a = a;
                worst_e = e;
            }
        }
    }
    const double mean_abs =
        sum_abs / static_cast<double>(n_mels * n_frames);

    std::fprintf(stdout,
                 "frontend_smoke: shape=[%d, %d]  max_abs=%.6e  mean_abs=%.6e  "
                 "(tolerances: max %.0e mean %.0e)\n",
                 n_mels, n_frames, max_abs, mean_abs, kMaxAbsTol, kMeanAbsTol);

    if (nan_count > 0) {
        std::fprintf(stderr,
                     "FAIL %d NaN/Inf elements in mel output\n",
                     nan_count);
        ++g_failures;
    }
    if (max_abs > kMaxAbsTol) {
        std::fprintf(stderr,
                     "FAIL max abs diff %.6e > %.0e\n"
                     "  worst at [%d, %d]: actual=%.7f expected=%.7f diff=%.6e\n",
                     max_abs, kMaxAbsTol,
                     worst_m, worst_t, worst_a, worst_e, max_abs);
        ++g_failures;
    }
    if (mean_abs > kMeanAbsTol) {
        std::fprintf(stderr,
                     "FAIL mean abs diff %.6e > %.0e\n",
                     mean_abs, kMeanAbsTol);
        ++g_failures;
    }

    if (g_failures > 0) {
        std::fprintf(stderr, "frontend_smoke: %d failures\n", g_failures);
        return EXIT_FAILURE;
    }
    std::fprintf(stdout, "frontend_smoke: ok\n");
    return EXIT_SUCCESS;
}
