// sentencepiece_bpe_parity.cpp - Tokenizer::encode_sentencepiece_bpe
// against ids from the reference `sentencepiece` library.
//
// Fixtures: tests/fixtures/sentencepiece_bpe/<name>.jsonl, one
// {"text": ..., "ids": [...]} per line, generated by
// scripts/gen_sentencepiece_bpe_fixture.py. Only the GGUF's tokenizer KVs
// are read (no weights). Gated per model:
//   TRANSCRIBE_CANARY_1B_V2_GGUF  -> canary-1b-v2.jsonl (single SentencePiece)
//   TRANSCRIBE_CANARY_FLASH_GGUF  -> canary-flash-en.jsonl (English sub-vocab)
// Ad hoc: sentencepiece_bpe_parity <gguf> <fixture.jsonl> [lo hi rmws].

#include "gguf.h"
#include "transcribe-tokenizer.h"

#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <string>
#include <vector>

namespace {

struct Case {
    std::string          text;
    std::vector<int32_t> ids;
};

// Minimal parser for the fixture's own JSON lines: a "text" string (with
// \\, \", \t, \n, \uXXXX escapes) and an "ids" integer array.
bool parse_line(const std::string & line, Case & out) {
    size_t p = line.find("\"text\": \"");
    if (p == std::string::npos) {
        return false;
    }
    p += 9;
    out.text.clear();
    while (p < line.size() && line[p] != '"') {
        char c = line[p++];
        if (c != '\\') {
            out.text += c;
            continue;
        }
        const char e = line[p++];
        if (e == 'n') {
            out.text += '\n';
        } else if (e == 't') {
            out.text += '\t';
        } else if (e == 'u') {
            const unsigned cp = static_cast<unsigned>(std::strtoul(line.substr(p, 4).c_str(), nullptr, 16));
            p += 4;
            if (cp < 0x80) {
                out.text += static_cast<char>(cp);
            } else if (cp < 0x800) {
                out.text += static_cast<char>(0xC0 | (cp >> 6));
                out.text += static_cast<char>(0x80 | (cp & 0x3F));
            } else {
                out.text += static_cast<char>(0xE0 | (cp >> 12));
                out.text += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
                out.text += static_cast<char>(0x80 | (cp & 0x3F));
            }
        } else {
            out.text += e;
        }
    }
    p = line.find("\"ids\": [", p);
    if (p == std::string::npos) {
        return false;
    }
    p += 8;
    out.ids.clear();
    while (p < line.size() && line[p] != ']') {
        char * end = nullptr;
        out.ids.push_back(static_cast<int32_t>(std::strtol(line.c_str() + p, &end, 10)));
        p = static_cast<size_t>(end - line.c_str());
        while (p < line.size() && (line[p] == ',' || line[p] == ' ')) {
            ++p;
        }
    }
    return true;
}

// Returns the number of mismatches, or -1 when the inputs cannot be loaded.
int run(const char * gguf_path, const std::string & fixture, int lo, int hi, bool rmws) {
    gguf_init_params gp{};
    gp.no_alloc      = true;
    gp.ctx           = nullptr;
    gguf_context * g = gguf_init_from_file(gguf_path, gp);
    if (g == nullptr) {
        std::fprintf(stderr, "cannot read %s\n", gguf_path);
        return -1;
    }
    transcribe::Tokenizer tok;
    const bool            loaded = tok.load(g) == TRANSCRIBE_OK;
    gguf_free(g);
    std::ifstream f(fixture);
    if (!loaded || !f) {
        std::fprintf(stderr, "cannot load tokenizer or fixture %s\n", fixture.c_str());
        return -1;
    }
    int         failures = 0, n = 0;
    std::string line;
    while (std::getline(f, line)) {
        Case c;
        if (!parse_line(line, c)) {
            continue;
        }
        ++n;
        std::vector<int32_t> got;
        if (tok.encode_sentencepiece_bpe(c.text, got, lo, hi, rmws) != TRANSCRIBE_OK || got != c.ids) {
            ++failures;
            std::fprintf(stderr, "FAIL \"%s\"\n  expected:", c.text.c_str());
            for (int32_t id : c.ids) {
                std::fprintf(stderr, " %d", id);
            }
            std::fprintf(stderr, "\n  actual:  ");
            for (int32_t id : got) {
                std::fprintf(stderr, " %d", id);
            }
            std::fprintf(stderr, "\n");
        }
    }
    std::fprintf(stderr, "%s: %d/%d match\n", fixture.c_str(), n - failures, n);
    return failures;
}

}  // namespace

int main(int argc, char ** argv) {
    if (argc >= 3) {
        const int  lo   = argc >= 5 ? std::atoi(argv[3]) : 0;
        const int  hi   = argc >= 5 ? std::atoi(argv[4]) : -1;
        const bool rmws = argc >= 6 && std::atoi(argv[5]) != 0;
        return run(argv[1], argv[2], lo, hi, rmws) == 0 ? EXIT_SUCCESS : EXIT_FAILURE;
    }
    const std::string dir = std::string(TRANSCRIBE_TEST_FIXTURES_DIR) + "/sentencepiece_bpe/";

    struct Gate {
        const char * env;
        const char * fixture;
        int          lo, hi;
        bool         rmws;  // the SentencePiece model's remove_extra_whitespaces
    };

    // canary-1b/180m-flash: the English sub-vocab is lang_offsets[1] = 1152,
    // 1024 pieces (stt.canary.tokenizer.lang_*).
    const Gate gates[] = {
        { "TRANSCRIBE_CANARY_1B_V2_GGUF", "canary-1b-v2.jsonl",    0,    -1,   false },
        { "TRANSCRIBE_CANARY_FLASH_GGUF", "canary-flash-en.jsonl", 1152, 2176, true  },
    };
    int ran = 0, failures = 0;
    for (const Gate & gate : gates) {
        const char * path = std::getenv(gate.env);
        if (path == nullptr || path[0] == '\0') {
            continue;
        }
        ++ran;
        const int r = run(path, dir + gate.fixture, gate.lo, gate.hi, gate.rmws);
        failures += r < 0 ? 1 : r;
    }
    if (ran == 0) {
        std::fprintf(stderr, "sentencepiece_bpe_parity: no model env set; skipping\n");
        return 77;
    }
    return failures == 0 ? EXIT_SUCCESS : EXIT_FAILURE;
}
