//! Workspace automation for the Rust bindings.
//!
//! `cargo xtask bindgen`          regenerate the committed FFI bindings
//! `cargo xtask bindgen --check`  fail if the committed bindings are stale
//!
//! The committed output lives at `bindings/rust/sys/src/transcribe_sys.rs`.
//! It is generated from `include/transcribe/extensions.h` (the flattened
//! public surface) and pinned to `include/transcribe.abihash`: the generated
//! header embeds the hash, so ANY public-ABI change moves either the bindgen
//! output or the embedded hash, and the `--check` diff goes red. This is the
//! Rust arm of the cross-binding drift gate (notes/bindings-requirements.md §2).
//!
//! Comments are disabled and a fixed enum style is used so the output is
//! deterministic across libclang versions; rustfmt formats it for review.

use std::path::{Path, PathBuf};
use std::process::ExitCode;

const GENERATED: &str = "bindings/rust/sys/src/transcribe_sys.rs";

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let check = args.iter().any(|a| a == "--check");
    match args.first().map(String::as_str) {
        Some("bindgen") => run_bindgen(check),
        _ => {
            eprintln!("usage: cargo xtask bindgen [--check]");
            ExitCode::from(2)
        }
    }
}

fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR = <root>/bindings/rust/xtask
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("repo root above bindings/rust/xtask")
        .to_path_buf()
}

fn run_bindgen(check: bool) -> ExitCode {
    let root = repo_root();
    let generated = generate(&root);
    let target = root.join(GENERATED);

    if check {
        let committed = std::fs::read_to_string(&target).unwrap_or_default();
        if committed == generated {
            println!("xtask: {GENERATED} is up to date");
            ExitCode::SUCCESS
        } else {
            eprintln!(
                "xtask: {GENERATED} is STALE.\n\
                 The public header or its ABI digest changed. Regenerate with:\n\
                 \n    cargo xtask bindgen\n\n\
                 and review + commit the result."
            );
            ExitCode::FAILURE
        }
    } else {
        std::fs::write(&target, generated).expect("write generated bindings");
        println!("xtask: wrote {GENERATED}");
        ExitCode::SUCCESS
    }
}

fn generate(root: &Path) -> String {
    let include = root.join("include");
    let header = include.join("transcribe/extensions.h");
    let abihash = std::fs::read_to_string(include.join("transcribe.abihash"))
        .expect("read include/transcribe.abihash");
    let abihash = abihash.trim();

    let bindings = bindgen::Builder::default()
        .header(header.to_string_lossy())
        .clang_arg(format!("-I{}", include.display()))
        // Determinism: comment extraction varies by libclang version, so the
        // committed file would drift across machines if we kept doc comments.
        .generate_comments(false)
        // FFI-safe enums: a NewType is a transparent integer wrapper, so an
        // out-of-range value from C is never UB (the safe crate validates at
        // the public boundary — the "never trust transmute" rule).
        .default_enum_style(bindgen::EnumVariation::NewType {
            is_bitfield: false,
            is_global: false,
        })
        .prepend_enum_name(false)
        // Only emit declarations from our own headers (skip stdint/stddef).
        .allowlist_file(r".*/include/transcribe\.h")
        .allowlist_file(r".*/include/transcribe/.*\.h")
        // Compile-time layout assertions (free belt-and-suspenders; the
        // per-field check is otherwise waived for bindgen).
        .layout_tests(true)
        .generate()
        .expect("bindgen generate");

    let banner = format!(
        "// @generated by `cargo xtask bindgen` from include/transcribe/extensions.h\n\
         // DO NOT EDIT BY HAND. Regenerate: `cargo xtask bindgen`.\n\
         // Pinned to include/transcribe.abihash = {abihash}\n\
         \n\
         /// The public-ABI digest these bindings were generated against\n\
         /// (sha256/16 over the normalized FFI surface). The load-time version\n\
         /// gate and the CI drift check both anchor on this value.\n\
         pub const PUBLIC_HEADER_HASH: &str = \"{abihash}\";\n\
         \n"
    );
    format!("{banner}{bindings}")
}
