#!/usr/bin/env python3
"""gen_vectors.py - C++ test vectors from the silero-vad 6.2.3 reference.

    uv run --project scripts/envs/silero_vad scripts/vad/gen_vectors.py

tests/fixtures/vad_segment_vectors.inc (tests/vad_dispatch_unit.cpp):
get_speech_timestamps_from_probs on hand-picked members of a seeded random
set. Together they cover every reachable branch of the reference and catch
every detectable mutant of the C++ port; they include 0.6 / 0.45 thresholds
(not exact in float), zero padding, partial last frames and an empty result.

tests/fixtures/vad_iterator_vectors.inc (tests/vad_iterator_unit.cpp): the
upstream VADIterator driven by a stub returning float32 probabilities.
"""

from __future__ import annotations

import random
from pathlib import Path

import silero_vad
import torch
from silero_vad import get_speech_timestamps_from_probs
from silero_vad.utils_vad import VADIterator

FIXTURES = Path(__file__).resolve().parents[2] / "tests" / "fixtures"
FRAME = 512
LEVELS = 16  # probabilities on a 1/16 grid (exact in float32), one char per frame: 'a' + 16 * p
ALIGNED = [32, 64, 96, 128]  # ms whose sample count is a multiple of FRAME

# Indices into the seeded 360-vector sequence below.
SEGMENT_VECTORS = [8, 11, 13, 28, 67, 103, 104, 154, 222, 261, 336]
N_GENERATED = max(SEGMENT_VECTORS) + 1

# name, frame, threshold, min_silence_ms, speech_pad_ms, probabilities
ITERATOR_CASES = [
    ("start-at-threshold", 512, .5, 100, 30, [0, .5, .5, 0, 0, 0, 0, 0, .5, 0, 0, 0, 0, 0]),
    ("exit-equality-is-not-silence", 512, .4, 32, 0, [.4, .25, .25, .125, .25, .125]),
    ("float32-vs-double-boundary", 512, .6, 0, 0, [.6, .45, .44999999, .6]),
    ("speech-cancels-pending-end", 512, .5, 64, 30, [.5, 0, .5, 0, 0, 0]),
    ("middle-band-keeps-pending-end", 512, .5, 64, 30, [.5, 0, .375, .375, 0]),
    ("middle-band-does-not-start", 512, .5, 64, 30, [.375, .375, .5, .375, .375, .375]),
    ("no-offline-exit-floor", 512, .1, 0, 0, [.125, 0, 0, 0, 0]),
    ("zero-start-threshold", 512, 0, 0, 30, [0, 0, 0]),
    ("padding-can-overlap", 512, 1, 0, 200, [0, 1, 0, 1, 0, 1]),
    ("silence-has-no-events", 512, .5, 100, 30, [0, 0, 0]),
    ("active-speech-at-eof", 512, .5, 100, 30, [.5, .5, .5]),
    ("pending-silence-at-eof", 512, .5, 100, 30, [.5, 0, 0]),
    ("empty-input", 512, .5, 0, 0, []),
    ("exact-silence-duration", 1600, .5, 100, 30, [.5, 0, 0, .5, 0, 0]),
    ("small-frame-clock", 8, .5, 0, 0, [0, .5, 0, .5, 0]),
]


def walk(rng: random.Random, n: int) -> list[int]:
    level = rng.choice([1, 15])
    out = []
    for _ in range(n):
        if rng.random() < 0.08:
            level = rng.choice([0, 2, 4, 5, 6, 8, 10, 12, 14, 16])
        out.append(max(0, min(LEVELS, level + rng.randint(-1, 1))))
    return out


def bursts(rng: random.Random, n: int) -> list[int]:
    out: list[int] = []
    speech = rng.random() < 0.5
    while len(out) < n:
        k = rng.choice([1, 2, 3, 4, 6, 10]) if not speech else rng.choice([2, 5, 8, 20, 40])
        out += [rng.choice([12, 16]) if speech else rng.choice([0, 1, 4]) for _ in range(k)]
        speech = not speech
    return out[:n]


def long_speech(rng: random.Random, n: int) -> list[int]:
    out: list[int] = []
    gaps = rng.sample([1, 2, 3, 4], 2)
    while len(out) < n:
        out += [16] * rng.randint(3, 25)
        out += [0] * rng.choice(gaps)
    return out[:n]


def split_params(rng: random.Random) -> dict:
    return {
        "threshold": 0.5,
        "neg_threshold": None,
        "min_speech_ms": rng.choice([0, 250]),
        "min_silence_ms": rng.choice([500, 1000]),
        "speech_pad_ms": rng.choice([0, 30]),
        "max_speech_ms": rng.choice([1000, 1500, 2048, 3000]),
        "min_silence_at_max_speech_ms": rng.choice([0, 32, 64, 98]),
        "use_max_possible_silence": rng.choice([True, True, False]),
    }


def params(rng: random.Random) -> dict:
    p = {
        "threshold": rng.choice([0.5, 0.5, 0.25, 0.375, 0.75, 0.6]),
        "neg_threshold": rng.choice([None, None, 0.125, 0.25, 0.3125, 0.45]),
        "min_speech_ms": rng.choice([250, 0, 100, 1000] + ALIGNED),
        "min_silence_ms": rng.choice([100, 0, 50, 500] + ALIGNED),
        "speech_pad_ms": rng.choice([30, 0, 200, 16, 32, 48]),
        "max_speech_ms": rng.choice([0, 0, 1000, 2500, 5000, 1024, 2048, 1500]),
        "min_silence_at_max_speech_ms": rng.choice([98, 0, 300] + ALIGNED),
        "use_max_possible_silence": rng.choice([True, False]),
    }
    if p["neg_threshold"] is not None and p["neg_threshold"] > p["threshold"]:
        p["neg_threshold"] = None
    return p


def segment_vectors() -> list[str]:
    rng = random.Random(6_2_3)
    lines = [
        f"// Generated by scripts/vad/gen_vectors.py from silero-vad {silero_vad.__version__}",
        "// get_speech_timestamps_from_probs. Do not edit.",
        "// {threshold, neg_threshold (-1 = default), min_speech_ms, min_silence_ms, speech_pad_ms,",
        "//  max_speech_ms, min_silence_at_max_speech_ms, use_max_possible_silence, n_samples,",
        "//  probs ('a' + 16 * p per frame), segments (start, end pairs)}",
    ]
    # Every vector is drawn so the random stream (and so each index) is stable.
    for v in range(N_GENERATED):
        n = rng.randint(20, 400)
        kind = v % 3
        q = (walk, bursts, long_speech)[kind](rng, n)
        n_samples = n * FRAME - rng.choice([0, 0, 1, rng.randint(0, FRAME - 1)])
        p = split_params(rng) if kind == 2 else params(rng)
        if v not in SEGMENT_VECTORS:
            continue
        segs = get_speech_timestamps_from_probs(
            [k / LEVELS for k in q],
            sampling_rate=16000,
            threshold=p["threshold"],
            neg_threshold=p["neg_threshold"],
            min_speech_duration_ms=p["min_speech_ms"],
            min_silence_duration_ms=p["min_silence_ms"],
            speech_pad_ms=p["speech_pad_ms"],
            max_speech_duration_s=p["max_speech_ms"] / 1000 if p["max_speech_ms"] else float("inf"),
            min_silence_at_max_speech=p["min_silence_at_max_speech_ms"],
            use_max_poss_sil_at_max_speech=p["use_max_possible_silence"],
            audio_length_samples=n_samples,
        )
        neg = -1.0 if p["neg_threshold"] is None else p["neg_threshold"]
        flat = [x for s in segs for x in (s["start"], s["end"])]
        lines.append(
            f"{{ {p['threshold']!r}, {neg!r}, {p['min_speech_ms']}, {p['min_silence_ms']}, {p['speech_pad_ms']}, "
            f"{p['max_speech_ms']}, {p['min_silence_at_max_speech_ms']}, "
            f"{'true' if p['use_max_possible_silence'] else 'false'}, {n_samples},\n"
            f"  \"{''.join(chr(ord('a') + k) for k in q)}\",\n"
            f"  {{ {', '.join(map(str, flat))} }} }},")
    return lines


class ProbabilityModel:
    def __init__(self, probabilities):
        self.probabilities = probabilities
        self.resets = 0

    def reset_states(self):
        self.index = 0
        self.resets += 1

    def __call__(self, x, sampling_rate):
        p = self.probabilities[self.index]
        self.index += 1
        return torch.tensor(p, dtype=torch.float32)


def iterator_vectors() -> list[str]:
    lines = [f"// Generated by scripts/vad/gen_vectors.py; silero-vad {silero_vad.__version__} VADIterator.",
             "// Stub probability model; float32 .item() inputs, samples (not seconds).",
             "// {name, frame, threshold, silence_ms, pad_ms, probs, {type, sample, detection_frame}, triggered}"]
    for name, frame, threshold, silence, pad, probs in ITERATOR_CASES:
        model = ProbabilityModel(probs)
        it = VADIterator(model, threshold=threshold, min_silence_duration_ms=silence, speech_pad_ms=pad)
        events = []
        for i in range(len(probs)):
            event = it(torch.zeros(frame))
            if event:
                kind, sample = next(iter(event.items()))
                events.append(f"{{ TRANSCRIBE_VAD_EVENT_{kind.upper()}, {sample}, {i} }}")
        assert model.resets == 1, "END must not reset the recurrent model"
        floats = ", ".join(f"{float(p)!r}f" for p in probs)
        lines.append(f'{{ "{name}", {frame}, {threshold!r}, {silence}, {pad},\n  {{ {floats} }},\n'
                     f"  {{ {', '.join(events)} }}, {'true' if it.triggered else 'false'} }},")
    return lines


def main() -> int:
    if silero_vad.__version__ != "6.2.3":
        raise SystemExit(f"error: silero-vad {silero_vad.__version__}; vectors are pinned to 6.2.3")
    for name, lines in (("vad_segment_vectors.inc", segment_vectors()),
                        ("vad_iterator_vectors.inc", iterator_vectors())):
        (FIXTURES / name).write_text("\n".join(lines) + "\n")
        print(f"wrote {FIXTURES / name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
