#!/usr/bin/env python3
"""Pin the C probability policy to the actual upstream VADIterator (no model).

uv run --project scripts/envs/silero_vad scripts/vad/gen_iterator_vectors.py

The stub returns float32 probabilities as a real model does. No translated
Python policy is used; checked-in vectors run in the default C++ tests with
no Python/torch runtime dependency. Regeneration requires silero-vad==6.2.3.
"""
from pathlib import Path

import silero_vad
import torch
from silero_vad.utils_vad import VADIterator

OUT = Path(__file__).resolve().parents[2] / "tests/fixtures/vad_iterator_vectors.inc"


class ProbabilityModel:
    def __init__(self, probabilities):
        self.probabilities = probabilities
        self.resets = 0

    def reset_states(self):
        self.index = 0
        self.resets += 1

    def __call__(self, x, sampling_rate):
        assert sampling_rate == 16000
        p = self.probabilities[self.index]
        self.index += 1
        return torch.tensor(p, dtype=torch.float32)


def main():
    assert silero_vad.__version__ == "6.2.3"
    cases = [
        ("start-at-threshold", 512, .5, 100, 30, [0, .5, .5, 0, 0, 0, 0, 0, .5, 0, 0, 0, 0, 0]),
        ("exit-equality-is-not-silence", 512, .4, 32, 0, [.4, .25, .25, .125, .25, .125]),
        ("float32-vs-double-boundary", 512, .6, 0, 0, [.6, .45, .44999999, .6]),
        ("speech-cancels-pending-end", 512, .5, 64, 30, [.5, 0, .5, 0, 0, 0]),
        ("middle-band-keeps-pending-end", 512, .5, 64, 30, [.5, 0, .375, .375, 0]),
        ("middle-band-does-not-start", 512, .5, 64, 30, [.375, .375, .5, .375, .375, .375]),
        ("no-offline-exit-floor", 512, .1, 0, 0, [.125, 0, 0, 0, 0]),
        ("zero-start-threshold", 512, 0, 0, 30, [0, 0, 0]),
        ("padding-can-overlap", 512, 1, 0, 200, [0, 1, 0, 1, 0, 1]),
        ("silence-has-no-events", 512, .5, 100, 30, [0, 0, 0]),
        ("active-speech-at-eof", 512, .5, 100, 30, [.5, .5, .5]),
        ("pending-silence-at-eof", 512, .5, 100, 30, [.5, 0, 0]),
        ("empty-input", 512, .5, 0, 0, []),
        ("exact-silence-duration", 1600, .5, 100, 30, [.5, 0, 0, .5, 0, 0]),
        ("small-frame-clock", 8, .5, 0, 0, [0, .5, 0, .5, 0]),
    ]
    lines = ["// Generated by scripts/vad/gen_iterator_vectors.py; silero-vad 6.2.3 VADIterator.",
             "// Stub probability model; float32 .item() inputs, samples (not seconds).",
             "// {name, frame, threshold, silence_ms, pad_ms, probs, {type, sample, detection_frame}, triggered}"]
    total = 0
    for name, frame, threshold, silence, pad, probs in cases:
        model = ProbabilityModel(probs)
        it = VADIterator(model, threshold=threshold, min_silence_duration_ms=silence, speech_pad_ms=pad)
        chunk = torch.zeros(frame)
        events = []
        for i in range(len(probs)):
            event = it(chunk)
            if event:
                kind, sample = next(iter(event.items()))
                events.append(f"{{ TRANSCRIBE_VAD_EVENT_{kind.upper()}, {sample}, {i} }}")
        # END must not reset the recurrent model.
        assert model.resets == 1
        total += len(events)
        floats = ", ".join(f"{float(p)!r}f" for p in probs)
        lines.append(f'{{ "{name}", {frame}, {threshold!r}, {silence}, {pad},\n  {{ {floats} }},\n'
                     f"  {{ {', '.join(events)} }}, {'true' if it.triggered else 'false'} }},")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}: {len(cases)} vectors, {total} events")


if __name__ == "__main__":
    main()
